trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Premium with MSDN(Converted to EA) - Theile(ed623955-fa27-48cc-b3ca-fc3a4e010c97)'
    appType: 'webApp'
    WebAppName: 'sheetyapp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
